### ISSUE TITLE
This works on Android also right?

### ISSUE THREAD

**Issue by satvikmaker** [johanneslumpe/react-native-selectablesectionlistview#12]
Hi, I just wanted to know, if this is purely a JS utility. It works on Android also right? I am having some issues getting this up and running, so wanted to clarify.

**Comment by johanneslumpe** [comment]
@bozzmob I would assume that it should just work. I guess the main issue is that the lib isn't updated to reflect this fact (no android entry file etc.) I'm currently quite busy, so a PR for this would of course be welcome :)

**Comment by satvikmaker** [comment]
Yes, Will have a look at it and update :)

**Comment by satvikmaker** [comment]
Thanks, I could make this work on android. [alphabetical list view](https://github.com/bozzmob/React-Native-Alphabetical-ListView)
