### ISSUE TITLE
Add `isFirst` and `isLast` prop to the Cell component

### ISSUE THREAD

**Issue by deanc** [johanneslumpe/react-native-selectablesectionlistview#6]
It would be useful to know whether the cell you are rendering is the first or last before a header. The reason for this being if you are recreating normal cell styling (e.g. Contacts iOS app) you have to have a bottom border on all cells, but then that border appears next to the next section header.

**Comment by johanneslumpe** [comment]
This landed with https://github.com/johanneslumpe/react-native-selectablesectionlistview/commit/aa95e19e1b95265f6b830cc282708928e566b78c
